server:
  port: 8000

external:
  client: default # can be rest-template or default
  base-url-pattern: https://api.exchangeratesapi.io/latest?base=%s&symbols=%s
#  params:
#    - "base=%s"
#    - "symbols=%s"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchange
    username: exchange
    password: exchange
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
